name: meteo_app
description: Application météo Flutter - L3GL ISI 2026

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- HTTP  ---
  dio: ^5.4.0
  json_annotation: ^4.8.1
  # ---- variables --
  flutter_dotenv: ^5.1.0

  # --- Maps ---
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  # --- Icônes & UI ---
  cupertino_icons: ^1.0.6

  #-- import lotties
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- Génération de code Retrofit ---
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/img/
    - assets/lottie/